Dockerfile
LICENSE
README.md

NB. this is a public repo licensed as MIT.
The Dockerfile is based off of node:12-alpine and then has a number of extra packages installed that are required by CI build jobs.

Create Dockerfile with useful CI tools

---

Dockerfile-expocli
README.md

expo-cli doubles the size of the image so not adding it to the default image, but this is a useful tool to have for expo projects.
Docker hub is configured to build this 2nd dockerfile with the tag 12-expocli.

Add an image variant including the expo-cli

---

Dockerfile-expocli
README.md

Expo builds frequently require some json manipulation, so adding jq as a useful utility.

Add jq to expocli variant of image

---

.semaphore/semaphore.yml
Dockerfile
Dockerfile-expocli

Use Semaphore to build the image and push to Docker Hub. Replaces Docker Hub's Autobuild, which is becoming unavailable
on the free account tier.
Also add a label to the image that Snyk can use to monitor the repo.
[ch982]

Build and deploy image using Semaphore

---

.semaphore/semaphore.yml
Dockerfile
Dockerfile-expocli
README.md

This adds the ability to build for node 14 and 16 and also updates alpine to 3.15

Update to build node for 14 and 16

---

.semaphore/semaphore.yml
README.md

We've now migrated all projects to be using node 16 and stopped using the v12 an v14 images in our CI. 
We can now stop building those versions and stop having to handle the maintenance burden that they've added to our security processes. 
I assume this will require us to either delete the published images and/or turn off the Snyk monitoring for those versions.

Remove creation of node 12 and 14 images

---

Dockerfile
Dockerfile-expocli
README.md

This upgrades packages that depend on `libcrypto1.1`, which upgrades `libcrypto1.1` to the fix version `1.1.1q-r0` for the `node` image, and the `node-expocli` image which is based on the former.
This fixes https://www.cve.org/CVERecord?id=CVE-2022-2097 (https://security.snyk.io/vuln/SNYK-ALPINE315-OPENSSL-2941810 and https://security.snyk.io/vuln/SNYK-ALPINE315-OPENSSL-2941810)

Upgrade libcrypto1.1 for security vulns (both images)

---

README.md

This PR will resolve the `expat/expat` vulnerabilities that were identified in `node:16` and `node:16-expocli`.  A fix already exists and the images just need to be rebuilt.
Building the `node` image locally and checking it with `snyk` returns 0 vulnerabilities.
Building the `node-expocli` image locally and checking it with `snyk` returns the `expat/expat` vulnerability.  This is only because the `Dockerfile` is referencing `countingup/node:16`.
Changing the base image in `Dockerfile-expocli` to reference the newly rebuilt node image that I used for testing returns 0 vulnerabilities when checked with `snyk`.

Updating readme to force rebuild and resolve security vulnerability

---

README.md

This should be installing a version of `qs` that's not affected by prototype pollution.
The Snyk Container command couldn't find the offending package after rebuilding the container, so this should be enough

Update for security vulnerabilities

---

README.md

Introduced through `python3/python3@3.9.15-r0`
Fixed in `python3/python3@3.9.16-r0`
```
...
✔ Tested 80 dependencies for known issues, no vulnerable paths found.
```

Rebuild to update for security vulns (python3)

---

Dockerfile
README.md

Fixes 3 HIGH and 6 MEDIUM CVEs by bumping the node version to 3.19.1

Update to Alpine 3.16 and node 16.19.1

---

Dockerfile
README.md

https://security.snyk.io/vuln/SNYK-ALPINE316-OPENSSL-5661567

Update libssl3 to fix CVE

---

Dockerfile
README.md

This package was added by mistake in https://github.com/Countingup/docker-node/pull/45 when trying to fix https://security.snyk.io/vuln/SNYK-ALPINE316-OPENSSL-5661567.
The image just needed a rebuild to get the latest `libcrypto1.1` and `libssl1.1` (Snyk recommends at least `1.1.1u-r0`), but the previous PR also added:
```
libssl3-3.0.9-r0 x86_64 {openssl3} (Apache-2.0) [installed]
libcrypto3-3.0.9-r0 x86_64 {openssl3} (Apache-2.0) [installed]
```
by removing this package, the `libcrypto1.1` and `libssl1.1` will remain at sufficient versions to fix the CVE:
```
libssl1.1-1.1.1u-r1 x86_64 {openssl} (OpenSSL) [installed]
libcrypto1.1-1.1.1u-r1 x86_64 {openssl} (OpenSSL) [installed]
```

Remove libssl3

---

.semaphore/semaphore.yml
Dockerfile
Dockerfile-expocli

Node v16 is reaching EOL on 2023-09-11. v18 is the next LTS version, supported until 2025-04-30.

Add build Node v18 image

---

README.md

Tested locally by creating an updated image. `curl` vulnerability is not reported anymore.

Rebuild image to update `curl`

---

README.md

This fixes:
- https://www.cve.org/CVERecord?id=CVE-2023-38545
- https://www.cve.org/CVERecord?id=CVE-2023-44487
Also tidied up a few bits in the readme to reference node 18 rather than 16 by default.

Rebuild image for security vulnerabilities

---

.semaphore/semaphore.yml
Dockerfile-expocli
README.md

This removes the `docker-node` image variant that includes `expo-cli` as it is no longer needed.

Stop building image variant with expo-cli included

---

Dockerfile

There are no new updates being built for 3.18, so update to 3.20 to get new security updates.
The pip installed by this is more picky about updating system dependencies and refuses to install without the extra flag. Ideally we'd move to install the aws cli v2 which is a direct apk package, but this requires more care to ensure compatibility with CI scripts, so leaving as a v1 CLI for now.

Update base image to alpine 3.20

---

README.md

- Fixed some spellings of 'update' from 'udpate', formatted table and added entry for this.
- Rebuild for curl sec vuln tested with snyk locally
Note: There are other vulns that are currently ignored WRT which are fixed by update to v20/22

Rebuild for curl sec vuln

---

Dockerfile

It is recommended to install the v2 cli with apk rather than with pip.
Latest version for alpine 3.20 is aws-cli 2.15.57-r0
[skip-sc][sc-27646]

Update aws-cli to 2.15
