Countingup/docker-node

Dockerfile
README.md

So I can use it to grab info from `package.json` files

added jq to base Dockerfile

---

README.md

https://github.com/expo/expo-cli/compare/expo-cli%404.12.12...expo-cli%404.13.0
Not convinced this will actually clear all the vulns & licence issues, but hopefully will remove a few.

Rebuild to update expo-cli for security vulns

---

README.md

Resolved vuln:
https://security.snyk.io/vuln/SNYK-ALPINE315-EXPAT-2393733
Introduced:
From: git/git@2.34.1-r0 > expat/expat@2.4.3-r0
From: python3/python3@3.9.7-r4 > expat/expat@2.4.3-r0

Rebuild to update base image for security vulns

---

README.md

Fixes [CVE-2018-25032](https://security.snyk.io/vuln/SNYK-ALPINE315-ZLIB-2434420)

Rebuild to update base image for security vulnerabilities

---

Dockerfile
README.md

This updates busybox to fix [SNYK-ALPINE315-BUSYBOX-2440607](https://app.snyk.io/vuln/SNYK-ALPINE315-BUSYBOX-2440607)

Update busybox and rebuild for security vulns

---

README.md

This rebuilds to update expo-cli to fix the following issues flagged by Snyk:
- [SNYK-JS-TAR-1579147](https://app.snyk.io/vuln/SNYK-JS-TAR-1579147)
- [SNYK-JS-TAR-1579152](https://app.snyk.io/vuln/SNYK-JS-TAR-1579152)
- [SNYK-JS-TAR-1536528](https://app.snyk.io/vuln/SNYK-JS-TAR-1536528)

Rebuild to update expo-cli to 5.4.4

---

README.md

Test current image in our repository:
`snyk container test countingup/node:16`
```
...
Base image:        node:16.15.0-alpine3.15
...
Tested 80 dependencies for known issues, found 2 issues.
```
After rebuild and local test:
```
...
Base image:        node:16.15.1-alpine3.15
...
✔ Tested 80 dependencies for known issues, no vulnerable paths found.
```
Other versions:
```
...
Base image:        node:12.22.12-alpine3.15
...
✔ Tested 80 dependencies for known issues, no vulnerable paths found.
```

Rebuild to fix vulns in base image

---

README.md

Update the tag to point at version 16 instead of 12.

Update the Docker Image Size tag to point at 16

---

README.md

Rebuild to update base image for security vulns, fixes:
- https://security.snyk.io/vuln/SNYK-ALPINE316-ZLIB-2976176
- https://security.snyk.io/vuln/SNYK-ALPINE315-CURL-3011746

Rebuild images to fix zlib and curl CVE

---

README.md

Updating README to force rebuild of node images

---

README.md

```
Testing cup:node...
Organization:      countingup
Package manager:   apk
Target file:       Dockerfile
Project name:      docker-image|cup
Docker image:      cup:node
Platform:          linux/amd64
Base image:        node:16-alpine3.15
Licenses:          enabled
✓ Tested 82 dependencies for known issues, no vulnerable paths found.
```

Update base image to fix security vulns

---

README.md

Fix security vulnerabilities with image rebuild.

Rebuild to update for security vulns

---

README.md

https://security.snyk.io/vuln/SNYK-ALPINE316-CURL-5422114
https://security.snyk.io/vuln/SNYK-ALPINE316-CURL-5422115
https://security.snyk.io/vuln/SNYK-ALPINE316-CURL-5422116
https://security.snyk.io/vuln/SNYK-ALPINE316-CURL-5422121
https://security.snyk.io/vuln/SNYK-ALPINE316-CURL-5422123
https://security.snyk.io/vuln/SNYK-ALPINE316-CURL-5422125

Rebuild for curl vulnerabilities

---

README.md

Fixes: https://security.snyk.io/vuln/SNYK-ALPINE316-OPENSSH-5537077

Rebuild to fix openssh vulnerability

---

README.md

Resolves
- https://security.snyk.io/vuln/SNYK-ALPINE316-OPENSSL-5661567
- https://security.snyk.io/vuln/SNYK-ALPINE316-NCURSES-5606597
>**Note**
>This PR also puts the changelog into a table. No actual change other than adding another entry to the top
[sc-20472]

Rebuild to fix vulnerability

---

README.md

```
Testing cup:node16...
Organization:      michele.fiordispina
Package manager:   apk
Target file:       Dockerfile
Project name:      docker-image|cup
Docker image:      cup:node16
Platform:          linux/arm64
Base image:        node:16-alpine3.16
Licenses:          enabled
✔ Tested 65 dependencies for known issues, no vulnerable paths found.
```

Rebuild to update base image

---

README.md

Tested with `snyk container test` locally

Rebuild to update base image for security vulnerabilities 

---

.semaphore/semaphore.yml

update semaphore ubuntu image

---

.semaphore/semaphore.yml
Dockerfile-expocli
README.md

Reverts Countingup/docker-node#56

Revert "Stop building image variant with expo-cli included"

---

README.md

Tested with snyk container test.

Rebuild image to update vulnerable packages

---

README.md

Tested locally with `synk container test`

Rebuild to update base image for security vulnerability

---

README.md

Fixes:
- https://www.cve.org/CVERecord?id=CVE-2023-42363
- https://www.cve.org/CVERecord?id=CVE-2023-33460
- https://www.cve.org/CVERecord?id=CVE-2023-42365
- https://www.cve.org/CVERecord?id=CVE-2023-42364

Rebuild to update vulnerable packages

---

README.md

Tested with a locally built image

Rebuild image to fix security vulnerabilities (openssh)

---

README.md

Rebuild image to fix security vulnerabilities (expat)

---

README.md

Rebuild image to fix security vulnerabilities

---

README.md

Rebuild image for git vuln. Tested locally

Rebuild image for sec vuln
